platform :osx,‘10.11’
#source 'https://github.com/hanxiaoqing19910916/HanPodSpecs.git'
source 'https://github.com/CocoaPods/Specs.git'


target 'HChatForMac' do
    use_frameworks!
    pod 'Kingfisher'
    pod 'Alamofire'
    pod 'SnapKit'
    pod 'Socket.IO-Client-Swift', '~> 13.1.0'
end
